paulcwarren/spring-content

pom.xml, spring-content-fs/pom.xml, spring-content-fs/src/main/java/internal/org/springframework/content/fs/repository/DefaultFilesystemStoreImpl.java, spring-content-fs/src/test/java/internal/org/springframework/content/fs/repository/DefaultFilesystemStoresImplTest.java, spring-content-jpa/pom.xml, spring-content-jpa/src/main/java/internal/org/springframework/content/jpa/repository/DefaultJpaStoreImpl.java, spring-content-jpa/src/test/java/internal/org/springframework/content/jpa/store/DefaultJpaStoreImplTest.java, spring-content-mongo/pom.xml, spring-content-mongo/src/main/java/internal/org/springframework/content/mongo/repository/DefaultMongoStoreImpl.java, spring-content-mongo/src/test/java/internal/org/springframework/content/mongo/repository/DefaultMongoStoreImplTest.java, spring-content-rest/pom.xml, spring-content-s3/pom.xml, spring-content-s3/src/main/java/internal/org/springframework/content/s3/store/DefaultS3StoreImpl.java, spring-content-s3/src/test/java/internal/org/springframework/content/s3/store/DefaultS3StoreImplTest.java, spring-content-solr/pom.xml
Hello,
I made all unassiciate and unsetContent functions with the same logic for all stores.
Added also respective TestUnits.
Regards 
ladislav
=> Fixed unassociate and respective test units

spring-content-rest/src/main/asciidoc/rest.adoc
Just a typo in the spring-content-rest docs.
=> Fix gradle dependency typo

spring-versions-jpa/src/main/asciidoc/jpaversions-rest.adoc
Hey Paul,
I updated the ~/version asscidoc to use the property names associated with VerionInfo object. The version was created but the values were not set if I didn't use these names.
Regards, 
Lauren
=> Version attribute names need to match VersionInfo

spring-versions-jpa/src/main/java/org/springframework/versions/interceptors/OptimisticLockingInterceptor.java, spring-versions-jpa/src/test/java/org/springframework/versions/interceptors/OptimisticLockingInterceptorTest.java
=> When versioning, optimisticly lock setContent (with resource) invocations

pom.xml, spring-content-azure-storage/pom.xml, spring-content-azure-storage/src/test/java/internal/org/springframework/content/azure/it/AzureStorageIT.java, spring-content-azure-storage/src/test/java/internal/org/springframework/content/azure/it/Azurite.java, spring-content-s3/pom.xml, spring-content-s3/src/test/java/internal/org/springframework/content/s3/config/EnableS3StoresTest.java, spring-content-s3/src/test/java/internal/org/springframework/content/s3/it/LocalStack.java, spring-content-s3/src/test/java/internal/org/springframework/content/s3/it/S3StoreIT.java
Hi Paul, my curiosity got the better of me and I decided to look into the Azure docker container implementation.
It seemed obvious to me that it would be better to try it out with a real-world scenario, so I took the liberty of converting the Azure tests to use my test container implementation. There actually isn't much to this in the end but it now means the Azure tests could run without a pre-defined Azure set-up and would make development for spring-content noobs like myself easier moving forward.
I hope you don't mind that I have opened a PR but please feel free to reject it if this isn't a road you would want to go down.
Cheers, Andy.
=> Azurite TestContainer for Azure blob testing

spring-content-autoconfigure/src/main/java/internal/org/springframework/content/s3/boot/autoconfigure/S3ContentAutoConfiguration.java
- to avoid conflict with spring cloud aws messaging
Fixes #622
=> Rename the autoconfigured AmazonS3 bean

pom.xml, spring-content-autoconfigure/src/main/java/internal/org/springframework/content/s3/boot/autoconfigure/S3ContentAutoConfiguration.java, spring-content-autoconfigure/src/test/java/org/springframework/content/s3/boot/autoconfigure/ContentS3AutoConfigurationTest.java, spring-content-autoconfigure/src/test/java/org/springframework/content/s3/boot/defaultstorage/S3AutoConfigurationTest.java, spring-content-gcs/pom.xml, spring-content-s3/pom.xml, spring-content-s3/src/main/java/internal/org/springframework/content/s3/config/S3StoreFactoryBean.java, spring-content-s3/src/main/java/internal/org/springframework/content/s3/io/S3StoreResource.java, spring-content-s3/src/main/java/internal/org/springframework/content/s3/io/SimpleStorageNameUtils.java, spring-content-s3/src/main/java/internal/org/springframework/content/s3/io/SimpleStorageProtocolResolver.java, spring-content-s3/src/main/java/internal/org/springframework/content/s3/io/SimpleStorageResource.java, spring-content-s3/src/main/java/internal/org/springframework/content/s3/store/DefaultS3StoreImpl.java, spring-content-s3/src/main/java/org/springframework/content/s3/config/EnableS3ContentRepositories.java, spring-content-s3/src/main/java/org/springframework/content/s3/config/EnableS3Stores.java, spring-content-s3/src/main/java/org/springframework/content/s3/config/MultiTenantAmazonS3Provider.java, spring-content-s3/src/test/java/internal/org/springframework/content/s3/config/EnableS3StoresTest.java, spring-content-s3/src/test/java/internal/org/springframework/content/s3/config/S3StoreFactoryBeanTest.java, spring-content-s3/src/test/java/internal/org/springframework/content/s3/it/LocalStack.java, spring-content-s3/src/test/java/internal/org/springframework/content/s3/it/S3StoreIT.java, spring-content-s3/src/test/java/internal/org/springframework/content/s3/store/DefaultS3StoreImplTest.java
Bump to Spring Cloud 2021.0.0 and refactor onto aws sdk v2.  
This is a backward incompatible change because aws sdk v2 renamed AmazonS3 -> S2Client and moved the S3ObjectId class into a different package.  Both of which we expose to our clients.
=> Refactor onto aws sdk v2

spring-content-jpa/pom.xml
Rather than override it with exactly the same version!
=> Use the managed version of the h2 dependency

spring-content-azure-storage/pom.xml, spring-content-cmis/pom.xml, spring-content-commons/pom.xml, spring-content-elasticsearch/pom.xml, spring-content-fs/pom.xml, spring-content-gcs/pom.xml, spring-content-jpa/pom.xml, spring-content-mongo/pom.xml, spring-content-rest/pom.xml, spring-content-s3/pom.xml
The lombok annotation processor should be placed in the provided scope,
so its dependency is not propagated to projects that depend on
spring-content.
This matches with the installation instructions: https://projectlombok.org/setup/maven
Fixes #768
=> Put lombok in the provided scope

spring-content-commons/src/main/java/org/springframework/content/commons/io/RangeableResource.java, spring-content-rest/src/main/java/internal/org/springframework/content/rest/contentservice/AssociativeStoreContentService.java, spring-content-rest/src/main/java/internal/org/springframework/content/rest/contentservice/ContentStoreContentService.java, spring-content-rest/src/main/java/internal/org/springframework/content/rest/contentservice/StoreContentService.java, spring-content-rest/src/main/java/internal/org/springframework/content/rest/io/AssociatedStoreResource.java, spring-content-rest/src/main/java/internal/org/springframework/content/rest/io/AssociatedStoreResourceImpl.java, spring-content-s3/src/main/java/internal/org/springframework/content/s3/io/S3StoreResource.java, spring-content-s3/src/main/java/internal/org/springframework/content/s3/io/SimpleStorageResource.java, spring-content-s3/src/test/java/internal/org/springframework/content/s3/it/S3StoreIT.java
Only download the requested byte range and not the entire content.
=> Optimize byte range requests to S3 Storage

spring-content-s3/src/main/java/internal/org/springframework/content/s3/io/S3StoreResource.java, spring-content-s3/src/main/java/internal/org/springframework/content/s3/io/SimpleStorageResource.java, spring-content-s3/src/main/java/internal/org/springframework/content/s3/store/DefaultReactiveS3StoreImpl.java, spring-content-s3/src/main/java/internal/org/springframework/content/s3/store/DefaultS3StoreImpl.java, spring-content-s3/src/test/java/internal/org/springframework/content/s3/it/S3StoreIT.java
Possible solution that fixes paulcwarren/spring-content#67
=> Set Content-Type metadata in S3 from an Entity field annotated with `@MimeType`

spring-content-commons/src/main/java/org/springframework/content/commons/mappingcontext/ContentPropertyBuilderVisitor.java, spring-content-commons/src/test/java/org/springframework/content/commons/mappingcontext/ClassWalkerTest.java, spring-content-rest/src/test/java/internal/org/springframework/content/rest/support/TestEntity9.java, spring-content-rest/src/test/java/internal/org/springframework/content/rest/support/TestEntity9Repository.java, spring-content-rest/src/test/java/internal/org/springframework/content/rest/support/TestEntity9Store.java, spring-content-rest/src/test/java/it/internal/org/springframework/content/rest/controllers/ContentEntityRestEndpointsIT.java
=> fix: class walker should support empty path lookups for entities with a single content property of correlated attributes

spring-content-commons/src/main/java/internal/org/springframework/content/commons/repository/factory/StoreImpl.java
This PR fixes the issue, that in some `ContentStore`-methods with `PropertyPath` parameter, this parameter was not passed to the emitted events.
=> Specify PropertyPath in all content events emitted by PropertyPath accessors

spring-content-rest/src/main/java/internal/org/springframework/content/rest/contentservice/ContentStoreContentService.java
This PR moves the update of entity fields annotated with `@MimeType` and `@OriginalFileName` before setting of content in Spring Content REST.
This information may be neеded during content saving e.g.
- to arrange content into folders based on their contentType in custom storage location converters
- to https://github.com/paulcwarren/spring-content/pull/889
=> Update entity fields annotated with `@MimeType` and `@OriginalFileName` before setting of content

spring-content-commons/src/main/java/org/springframework/content/commons/mappingcontext/MappingContext.java, spring-content-rest/src/main/java/internal/org/springframework/content/rest/links/ContentLinksResourceProcessor.java, spring-content-rest/src/main/java/internal/org/springframework/content/rest/utils/StoreUtils.java, spring-content-rest/src/main/java/org/springframework/content/rest/config/HypermediaConfiguration.java, spring-content-rest/src/test/java/internal/org/springframework/content/rest/links/ContentLinksResourceProcessorIT.java
Use MappingContext to retrieve all URLs that are registered for content
properties, also for nested properties.
=> Add links to nested content properties

spring-content-rest/src/main/java/internal/org/springframework/content/rest/contentservice/ContentStoreContentService.java, spring-content-rest/src/main/java/internal/org/springframework/content/rest/controllers/StoreRestController.java, spring-content-rest/src/test/java/it/internal/org/springframework/content/rest/controllers/StoreRestEndpointsIT.java
This PR fixes a problem with using HTTP request content length when uploading files via multi-part form data PUT request. 
The content length should be set using multipart/form-data file size instead of HTTP request content length, so that content can be downloaded later with the correct file length in the HTTP response.
=> fix: use multi-part file size to set content length property

spring-content-rest/src/main/java/internal/org/springframework/content/rest/controllers/resolvers/DefaultEntityResolver.java
Fixes: 
1. initializes the Optional as empty, not as null object.
2. added [optional] exception handler for AccessDeniedException for throwing it. 
3. added [optional] (slf4j) logging 
First change fixes the two NullPointerExeception cases in method last return statement.   
a) when `invoker == null`  
b) AccessDeniedException or any Expection  other than ConverterNotFoundException is thrown.  
2.&3. are not necessary, but I think improve the code.
=> Fixes two NPE conditions in DefaultEntityResolver return statement

spring-content-azure-storage/src/main/java/internal/org/springframework/content/azure/config/AzureStorageConfiguration.java
The `AzureStorageConfiguration` may lead to exceptions due to circular references caused by the provider for the `PlacementService`.
Creating the instance during object creation (like in the `S3StoreConfiguration`) avoids this problem.
Closes #1431
=> fix(azure): avoid circular references in AzureStorageConfiguration

spring-content-azure-storage/src/main/java/internal/org/springframework/content/azure/config/AzureStorageFactoryBean.java, spring-content-gcs/src/main/java/internal/org/springframework/content/gcs/config/GCPStorageFactoryBean.java, spring-content-s3/src/main/java/internal/org/springframework/content/s3/config/S3StoreFactoryBean.java, spring-content-s3/src/test/java/internal/org/springframework/content/s3/config/S3StoreFactoryBeanTest.java
With the way that storage beans are created in Spring Content 3 constructor injection can fail when used inside `@DataJpaTest`s.
Fixes #1444
=> fix: ensure storage factory beans don't rely on constructor injection

spring-content-azure-storage/src/main/java/internal/org/springframework/content/azure/store/DefaultAzureStorageImpl.java, spring-content-azure-storage/src/test/java/internal/org/springframework/content/azure/it/AzureStorageIT.java, spring-content-commons/src/main/java/org/springframework/content/commons/mappingcontext/ContentProperty.java, spring-content-commons/src/main/java/org/springframework/content/commons/mappingcontext/ContentPropertyMappingContextVisitor.java, spring-content-commons/src/test/java/org/springframework/content/commons/mappingcontext/ClassWalkerTest.java, spring-content-fs/src/main/java/internal/org/springframework/content/fs/store/DefaultFilesystemStoreImpl.java, spring-content-fs/src/test/java/it/store/FilesystemStoreIT.java, spring-content-gcs/src/main/java/internal/org/springframework/content/gcs/store/DefaultGCPStorageImpl.java, spring-content-gcs/src/test/java/internal/org/springframework/content/gcs/it/GCPStorageIT.java, spring-content-jpa/src/main/java/internal/org/springframework/content/jpa/store/DefaultJpaStoreImpl.java, spring-content-jpa/src/test/java/internal/org/springframework/content/jpa/ContentStoreIT.java, spring-content-s3/src/main/java/internal/org/springframework/content/s3/store/DefaultS3StoreImpl.java, spring-content-s3/src/test/java/internal/org/springframework/content/s3/it/S3StoreIT.java
-  provides better support for null embedded content objects
Fixes #1480
=> feat: content property now uses setAutoGrowNestedPaths when setting ccontent

spring-content-azure-storage/pom.xml, spring-content-gcs/pom.xml
Add test scope to `junit `dependencies.
Closes #1541
=> fix(setup): do not add junit as compile dependency

spring-content-azure-storage/src/main/java/internal/org/springframework/content/azure/store/DefaultAzureStorageImpl.java, spring-content-azure-storage/src/test/java/internal/org/springframework/content/azure/it/AzureStorageIT.java, spring-content-commons/src/main/java/org/springframework/content/commons/mappingcontext/ContentProperty.java, spring-content-commons/src/main/java/org/springframework/content/commons/mappingcontext/ContentPropertyMappingContextVisitor.java, spring-content-commons/src/main/java/org/springframework/content/commons/utils/BeanUtils.java, spring-content-commons/src/test/java/org/springframework/content/commons/mappingcontext/ClassWalkerTest.java, spring-content-fs/src/main/java/internal/org/springframework/content/fs/store/DefaultFilesystemStoreImpl.java, spring-content-fs/src/test/java/it/store/FilesystemStoreIT.java, spring-content-gcs/src/main/java/internal/org/springframework/content/gcs/store/DefaultGCPStorageImpl.java, spring-content-gcs/src/test/java/internal/org/springframework/content/gcs/it/GCPStorageIT.java, spring-content-jpa/src/main/java/internal/org/springframework/content/jpa/store/DefaultJpaStoreImpl.java, spring-content-jpa/src/test/java/internal/org/springframework/content/jpa/ContentStoreIT.java, spring-content-jpa/src/test/java/internal/org/springframework/content/jpa/testsupport/models/ClaimForm.java, spring-content-mongo/src/main/java/internal/org/springframework/content/mongo/store/DefaultMongoStoreImpl.java, spring-content-mongo/src/test/java/internal/org/springframework/content/mongo/it/MongoStoreIT.java, spring-content-rest/src/test/java/internal/org/springframework/content/rest/it/AbstractRestIT.java, spring-content-rest/src/test/java/internal/org/springframework/content/rest/storedrenditions/StoredRenditionsRestIT.java, spring-content-rest/src/test/java/it/internal/org/springframework/content/rest/controllers/Content.java, spring-content-rest/src/test/java/it/internal/org/springframework/content/rest/controllers/NestedContentPropertiesRestEndpointsIT.java, spring-content-rest/src/test/java/it/internal/org/springframework/content/rest/controllers/NestedContentPropertyRestEndpointsIT.java, spring-content-rest/src/test/java/it/internal/org/springframework/content/rest/controllers/RestResourceMappedRestEndpointsIT.java, spring-content-rest/src/test/java/it/internal/org/springframework/content/rest/controllers/Version.java, spring-content-s3/src/main/java/internal/org/springframework/content/s3/store/DefaultReactiveS3StoreImpl.java, spring-content-s3/src/main/java/internal/org/springframework/content/s3/store/DefaultS3StoreImpl.java, spring-content-s3/src/test/java/internal/org/springframework/content/s3/it/S3StoreIT.java
=> When content is unset all storage now attempts to reset content length to its type's default value

spring-content-s3/src/main/java/internal/org/springframework/content/s3/io/SimpleStorageResource.java
The class `internal.org.springframework.content.s3.io.SimpleStorageResource.SimpleStorageOutputStream` seems to be pre-allocating 5MB for uploads to amazon S3. When used by several concurrent users to upload smaller files (~200KB), this eager-allocation seems to be using more memory than necessary. This results in OOM errors when the number of concurrent users is sufficiently high. 
Changing the implementation to use
`ByteArrayOutputStream currentOutputStream = new ByteArrayOutputStream()`
instead of 
`ByteArrayOutputStream currentOutputStream = new ByteArrayOutputStream(BUFFER_SIZE)`
should help, but if used in a system which usually uploads large files, this might introduce a penalty for growing the buffer from the initial 32 bytes pre-allocated by ByteArrayOutputStream.
Using …
=> Optimize memory usage during upload of smaller files to amazon S3

spring-content-rest/src/main/java/internal/org/springframework/content/rest/io/AssociatedStoreResourceImpl.java
Having Content-Disposition set to 'form-data' is only valid in multipart form submissions (in the request), never in a response.
In a response, the content-disposition should only be set to either 'attachment' or 'inline': https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition#as_a_response_header_for_the_main_body
Given the `name="attachment"` part of the current (incorrect) content-disposition header, I believe the goal was to have `content-disposition: attachment` set as header.
When there is no filename available for the content, `Content-Disposition: attachment` should be set as well to always force a download of the content, otherwise a browser would fall back to the default (which is `inline`).
Using `Content-Disposition: inline` is problematic for resources …
=> Correct content-disposition response header to be of type 'attachment'

spring-content-commons/src/main/java/org/springframework/content/commons/mappingcontext/ClassWalker.java, spring-content-commons/src/main/java/org/springframework/content/commons/mappingcontext/ContentPropertyMappingContextVisitor.java, spring-content-commons/src/test/java/org/springframework/content/commons/mappingcontext/ClassWalkerTest.java, spring-content-rest/src/main/java/internal/org/springframework/content/rest/mappingcontext/RestResourceMappingBuilder.java, spring-content-rest/src/test/java/internal/org/springframework/content/rest/mappings/RestResourceMappingBuilderTest.java
=> fix: rest and store mappingcontext now use a common property naming convention

spring-content-rest/src/main/java/internal/org/springframework/content/rest/io/AssociatedStoreResourceImpl.java
windows defaults to windows-1252 which is not compliant with rfc5987 that governs how to encode header fields
Fixes #1556
=> fix: now uses utf8 when setting content-dispostion filename

spring-content-autoconfigure/src/main/java/internal/org/springframework/content/rest/boot/autoconfigure/ContentRestAutoConfiguration.java, spring-content-rest/src/main/java/internal/org/springframework/content/rest/controllers/StoreRestController.java, spring-content-rest/src/main/java/internal/org/springframework/content/rest/io/StoreResource.java, spring-content-rest/src/main/java/internal/org/springframework/content/rest/links/ContentLinksResourceProcessor.java, spring-content-rest/src/main/java/org/springframework/content/rest/config/RestConfiguration.java
…estMvcAutoConfiguration so that our resource argumenthandler is added to the set of argumenthandlers before the terminal ProxyingHandlerMethodArgumentResolver
=> fix: ensure resource argument handler is before proxying handler argument resolver

spring-content-autoconfigure/src/main/java/internal/org/springframework/content/jpa/boot/autoconfigure/ContentJpaProperties.java, spring-content-autoconfigure/src/main/java/internal/org/springframework/content/jpa/boot/autoconfigure/JpaContentAutoConfiguration.java, spring-content-autoconfigure/src/test/java/org/springframework/content/jpa/boot/autoconfigure/ContentJpaAutoConfigurationTest.java, spring-content-autoconfigure/src/test/resources/default.properties, spring-content-jpa/src/main/java/internal/org/springframework/content/jpa/config/JpaStoreFactoryBean.java, spring-content-jpa/src/main/java/internal/org/springframework/content/jpa/store/DefaultJpaStoreImpl.java, spring-content-jpa/src/test/java/internal/org/springframework/content/jpa/store/DefaultJpaStoreImplTest.java
=> fix: add a copyBufferSize bean that allows configuration of the buffer size used by the jpa store copyLarge operation

spring-content-rest/src/main/java/org/springframework/data/rest/extensions/entitycontent/RepositoryEntityMultipartController.java, spring-content-rest/src/test/java/internal/org/springframework/content/rest/support/TestEntity4.java, spring-content-rest/src/test/java/it/internal/org/springframework/content/rest/controllers/ContentEntityRestEndpointsIT.java
=> fix multipart requests on entities with a non-default initialized @Version property

spring-content-rest/src/main/java/org/springframework/data/rest/extensions/entitycontent/RepositoryEntityMultipartController.java, spring-content-rest/src/test/java/internal/org/springframework/content/rest/support/EventListenerConfig.java, spring-content-rest/src/test/java/it/internal/org/springframework/content/rest/controllers/ContentEntityRestEndpointsIT.java
Spring content creates entities when using multipart post. However, it didn't send events for `onBeforeCreate` and `onAfterCreate`, so when you have custom validation you would bypass it with the multipart.
=> Send events when creating entities in multipart post

spring-content-rest/src/main/java/org/springframework/data/rest/extensions/entitycontent/RepositoryEntityMultipartConfiguration.java, spring-content-rest/src/main/java/org/springframework/data/rest/extensions/entitycontent/RepositoryEntityMultipartHttpMessageConverter.java
In spring-data-rest 4.4.0, the logic has changed and now
`RepresentationModel`is being passed to `canRead()` instead of
`PersistentEntityResource`.
To support both versions of spring-data-rest for a while, we can wrap all
message converters with one that supports multipart and converts it to
JSON. This also allows users to configure their own specific HttpMessageConverters
and have it automatically work with multipart as well.
=> Wrap all message converters from spring-data-rest with a multipart-supporting message converter

spring-content-encryption/src/main/java/internal/org/springframework/content/fragments/EncryptingContentStoreImpl.java, spring-content-encryption/src/main/java/org/springframework/content/encryption/EnvelopeEncryptionService.java, spring-content-encryption/src/test/java/org/springframework/content/encryption/LocalStack.java, spring-content-encryption/src/test/java/org/springframework/content/encryption/s3/EncryptionIT.java, spring-content-s3/src/main/java/internal/org/springframework/content/s3/io/PartialContentInputStream.java, spring-content-s3/src/main/java/internal/org/springframework/content/s3/io/SimpleStorageResource.java, spring-content-s3/src/test/java/internal/org/springframework/content/s3/io/PartialContentInputStreamTest.java, spring-content-s3/src/test/java/internal/org/springframework/content/s3/it/LocalStack.java, spring-content-s3/src/test/java/internal/org/springframework/content/s3/it/S3StoreIT.java
The PartialContentInputStream was a minimal implementation that worked
well when used directly with the spring byte-range support.
However, using the InputStream variant in any other place (like wrapping it for decryption),
the minimal implementation breaks down, requiring workarounds when
handling the encryption.
Using an implementation that is fully compliant with the InputStream
specifications makes implementation of a wrapping InputStream easier,
as no special provisions need to be made for a read method that
immediately reads the byte-range (instead of empty space before the start of the byte-range)
=> Fix S3 PartialContentInputStream to be compliant to InputStream specification

spring-content-gcs/src/main/java/internal/org/springframework/content/gcs/config/GCPStorageConfiguration.java
The `GCPStorageConfiguration` may lead to exceptions due to circular references caused by the provider for the `PlacementService`.
Creating the instance during object creation (like in the `S3StoreConfiguration`) avoids this problem.
Closes #2335
Supercedes: #2336
=> fix(gcp): avoid circular references in GCPStorageConfiguration (from cjnickel)
