paulcwarren/spring-content

spring-content-s3/src/main/java/org/springframework/content/s3/config/S3StoreConfigurer.java

Add a default implementation of configureS3ObjectIdResolvers

---

spring-content-rest/src/main/java/internal/org/springframework/content/rest/controllers/ResourceHandlerMethodArgumentResolver.java
spring-content-rest/src/main/java/internal/org/springframework/content/rest/controllers/StoreHandlerMethodArgumentResolver.java
spring-content-rest/src/main/java/internal/org/springframework/content/rest/controllers/resolvers/EntityResolver.java
spring-content-rest/src/main/java/internal/org/springframework/content/rest/controllers/resolvers/RevisionEntityResolver.java
spring-content-rest/src/main/java/org/springframework/content/rest/config/RestConfiguration.java
spring-versions-jpa/src/main/java/org/springframework/versions/impl/LockingAndVersioningRepositoryImpl.java

- this ensures the correct repository invoker is always used

Resource argument resolver now uses root resource information resolver for fetching entity

---

spring-content-commons/src/main/java/org/springframework/content/commons/utils/DomainObjectUtils.java
spring-content-rest/pom.xml
spring-content-rest/src/main/java/internal/org/springframework/content/rest/links/ContentLinksResourceProcessor.java
spring-content-rest/src/test/java/internal/org/springframework/content/rest/links/ContentLinksWithProjectionsIT.java

ContentLinksResourceProcessor now supports projections

---

spring-content-autoconfigure/src/main/java/internal/org/springframework/content/fs/boot/autoconfigure/FilesystemContentAutoConfigureRegistrar.java
spring-content-autoconfigure/src/main/java/internal/org/springframework/content/jpa/boot/autoconfigure/JpaContentAutoConfigureRegistrar.java
spring-content-autoconfigure/src/main/java/internal/org/springframework/content/mongo/boot/autoconfigure/MongoContentAutoConfigureRegistrar.java
spring-content-autoconfigure/src/main/java/internal/org/springframework/content/s3/boot/autoconfigure/S3ContentAutoConfigureRegistrar.java
spring-content-azure-storage/src/main/asciidoc/azure.adoc
spring-content-azure-storage/src/main/java/internal/org/springframework/content/azure/config/AzureStorageRegistrar.java
spring-content-commons/src/main/asciidoc/content-repositories.adoc
spring-content-commons/src/main/java/internal/org/springframework/content/commons/utils/StoreUtils.java
spring-content-commons/src/main/java/org/springframework/content/commons/config/AbstractStoreBeanDefinitionRegistrar.java
spring-content-commons/src/main/java/org/springframework/content/commons/utils/DomainObjectUtils.java
spring-content-commons/src/test/java/internal/org/springframework/content/commons/utils/StoreUtilsTest.java
spring-content-commons/src/test/java/org/springframework/content/commons/repository/factory/testsupport/TestStoresRegistrar.java
spring-content-fs/src/main/asciidoc/fs.adoc
spring-content-fs/src/main/java/internal/org/springframework/content/fs/config/FilesystemStoreRegistrar.java
spring-content-gcs/src/main/asciidoc/gcs.adoc
spring-content-gcs/src/main/java/internal/org/springframework/content/gcs/config/GCPStorageRegistrar.java
spring-content-jpa/src/main/asciidoc/jpa.adoc
spring-content-jpa/src/main/java/internal/org/springframework/content/jpa/config/JpaStoresRegistrar.java
spring-content-mongo/src/main/asciidoc/mongo.adoc
spring-content-mongo/src/main/java/internal/org/springframework/content/mongo/config/MongoContentRepositoriesRegistrar.java
spring-content-mongo/src/main/java/internal/org/springframework/content/mongo/config/MongoContentStoresRegistrar.java
spring-content-rest/pom.xml
spring-content-rest/src/main/java/internal/org/springframework/content/rest/links/ContentLinksResourceProcessor.java
spring-content-rest/src/test/java/internal/org/springframework/content/rest/links/ContentLinksWithProjectionsIT.java
spring-content-rest/src/test/java/internal/org/springframework/content/rest/support/mockstore/MockStoresRegistrar.java
spring-content-s3/src/main/asciidoc/s3.adoc
spring-content-s3/src/main/java/internal/org/springframework/content/s3/config/S3StoresRegistrar.java

- allowing users to control which storage module is used at runtime

Support for a spring.content.storage.type.default property

---

spring-content-rest/src/test/java/internal/org/springframework/content/rest/it/cachecontrol/CacheControlIT.java

Support for configuring cache control headers

---

spring-content-jpa/src/main/java/internal/org/springframework/content/jpa/config/JpaStoresRegistrar.java

Add override property value for JPA

---

spring-content-jpa/src/main/java/internal/org/springframework/content/jpa/io/PostgresBlobResource.java
spring-content-jpa/src/test/java/internal/org/springframework/content/jpa/io/PostgresBlobResourceIT.java

- delete its associated lob resources
Fixes #659

When deleting content from postgres

---

spring-content-cmis/src/main/java/internal/org/springframework/content/cmis/CmisServiceBridge.java
spring-content-cmis/src/test/java/org/springframework/content/cmis/integration/CmisTests.java
spring-content-cmis/src/test/java/org/springframework/content/cmis/integration/EnableCmisWithNavServiceTest.java
spring-content-cmis/src/test/java/org/springframework/content/cmis/integration/EnableCmisWithoutNavServiceTest.java

Deleting a folder should not try to delete a document

---

spring-content-cmis/src/main/java/internal/org/springframework/content/cmis/CmisServiceBridge.java
spring-content-cmis/src/main/java/internal/org/springframework/content/cmis/ContentCmisService.java
spring-content-cmis/src/test/java/org/springframework/content/cmis/integration/CmisTests.java
spring-content-rest/src/main/java/org/springframework/data/rest/versioning/LockingAndVersioningRestController.java
spring-versions-commons/src/main/java/org/springframework/versions/LockingAndVersioningRepository.java
spring-versions-jpa/src/main/java/org/springframework/versions/impl/LockingAndVersioningRepositoryImpl.java
spring-versions-jpa/src/test/java/org/springframework/versions/impl/JpaLockingAndVersioningRepositoryImplIT.java

- findAllVersions now returns an ordered (by id) list
Fixes #663
Tasks

Add deleteAllVersions

---

spring-content-autoconfigure/src/main/java/internal/org/springframework/content/fs/boot/autoconfigure/FilesystemContentAutoConfiguration.java
spring-content-autoconfigure/src/main/java/internal/org/springframework/content/jpa/boot/autoconfigure/JpaContentAutoConfiguration.java
spring-content-autoconfigure/src/main/java/internal/org/springframework/content/mongo/boot/autoconfigure/MongoContentAutoConfiguration.java
spring-content-autoconfigure/src/main/java/internal/org/springframework/content/s3/boot/autoconfigure/S3ContentAutoConfiguration.java
spring-content-autoconfigure/src/test/java/org/springframework/content/fs/boot/autoconfigure/ContentFilesystemAutoConfigurationTest.java
spring-content-autoconfigure/src/test/java/org/springframework/content/fs/boot/autoconfigure/FilesystemPropertiesTest.java
spring-content-autoconfigure/src/test/java/org/springframework/content/fs/boot/defaultstorage/FilesystemAutoConfigurationTest.java
spring-content-autoconfigure/src/test/java/org/springframework/content/jpa/boot/autoconfigure/ContentJpaAutoConfigurationTest.java
spring-content-autoconfigure/src/test/java/org/springframework/content/jpa/boot/autoconfigure/ContentJpaDatabaseInitializerTest.java
spring-content-autoconfigure/src/test/java/org/springframework/content/s3/boot/autoconfigure/ContentS3AutoConfigurationTest.java
spring-content-autoconfigure/src/test/java/org/springframework/content/s3/boot/defaultstorage/S3AutoConfigurationTest.java
spring-content-autoconfigure/src/test/java/org/springframework/support/TestUtils.java

- or the propery is not set at all
Fixes #667

Only autoconfigure storage if its default storage property is specified

---

pom.xml

Remove the unused logback classes dependency

---

spring-content-commons/src/main/java/org/springframework/content/commons/repository/factory/AbstractStoreFactoryBean.java
spring-content-s3/src/main/java/internal/org/springframework/content/s3/config/S3StoreFactoryBean.java

Inspect store interface to detect reactive

---

spring-content-commons/src/main/java/org/springframework/content/commons/mappingcontext/ContentPropertyBuilderVisitor.java
spring-content-commons/src/test/java/org/springframework/content/commons/mappingcontext/ClassWalkerTest.java

Don't walk enums

---

spring-content-commons/src/main/java/org/springframework/content/commons/mappingcontext/MappingContext.java
spring-content-rest/src/main/java/internal/org/springframework/content/rest/controllers/resolvers/DefaultEntityResolver.java
spring-content-rest/src/test/java/it/internal/org/springframework/content/rest/controllers/Content.java

Ensure shortcut link requests resolve to a content property where possible

---

spring-content-commons/src/main/java/org/springframework/content/commons/mappingcontext/ContentPropertyBuilderVisitor.java
spring-content-commons/src/test/java/org/springframework/content/commons/mappingcontext/ClassWalkerTest.java

when walking class structures
- Fixes #1047

Class walker uses a stack to record visited classes and prevent stack overflows

---

spring-content-commons/src/main/java/org/springframework/content/commons/mappingcontext/ContentPropertyBuilderVisitor.java
spring-content-commons/src/test/java/org/springframework/content/commons/mappingcontext/ClassWalkerTest.java
spring-content-rest/src/main/asciidoc/rest-store.adoc
spring-content-rest/src/main/java/internal/org/springframework/content/rest/contentservice/ContentStoreContentService.java
spring-content-rest/src/main/java/internal/org/springframework/content/rest/controllers/ResourceHandlerMethodArgumentResolver.java
spring-content-rest/src/main/java/internal/org/springframework/content/rest/controllers/resolvers/AssociativeStoreResourceResolver.java
spring-content-rest/src/main/java/internal/org/springframework/content/rest/controllers/resolvers/DefaultEntityResolver.java
spring-content-rest/src/main/java/internal/org/springframework/content/rest/controllers/resolvers/EntityResolution.java
spring-content-rest/src/main/java/internal/org/springframework/content/rest/controllers/resolvers/ResourceResolver.java
spring-content-rest/src/main/java/internal/org/springframework/content/rest/controllers/resolvers/RevisionEntityResolver.java
spring-content-rest/src/main/java/internal/org/springframework/content/rest/controllers/resolvers/StoreResourceResolver.java
spring-content-rest/src/main/java/internal/org/springframework/content/rest/io/AssociatedStoreResource.java
spring-content-rest/src/main/java/internal/org/springframework/content/rest/io/AssociatedStoreResourceImpl.java
spring-content-rest/src/main/java/internal/org/springframework/content/rest/links/ContentLinksResourceProcessor.java
spring-content-rest/src/test/java/internal/org/springframework/content/rest/links/ContentLinksResourceProcessorIT.java
spring-content-rest/src/test/java/internal/org/springframework/content/rest/storeresolver/StoreResolverRestConfigurationIT.java
spring-content-rest/src/test/java/it/internal/org/springframework/content/rest/controllers/ContentPropertyRestEndpointsIT.java

MappingContext now generates a single content path per content property

---

spring-content-cmis/src/main/java/internal/org/springframework/content/cmis/CmisServiceBridge.java
spring-content-cmis/src/test/java/org/springframework/content/cmis/integration/CmisTests.java

related to https://github.com/paulcwarren/spring-content/issues/1073

folder now supports cmis:description

---

spring-content-rest/src/main/java/internal/org/springframework/content/rest/controllers/StoreRestController.java

- not all resources support lastModified

Getting a resource's lastModified is safe

---

spring-content-commons/src/main/java/org/springframework/content/commons/mappingcontext/ContentPropertyMappingContextVisitor.java
spring-content-commons/src/test/java/org/springframework/content/commons/mappingcontext/ClassWalkerTest.java
spring-content-rest/src/test/java/internal/org/springframework/content/rest/links/ContentLinkRelIT.java
spring-content-rest/src/test/java/it/internal/org/springframework/content/rest/controllers/ContentEntityRestEndpointsIT.java

ClassWalker now defaults to calculating content property name greedily

---

pom.xml
spring-content-commons/src/main/java/internal/org/springframework/content/commons/storeservice/StoreInfoImpl.java
spring-content-commons/src/main/java/org/springframework/content/commons/repository/factory/AbstractStoreFactoryBean.java
spring-content-commons/src/main/java/org/springframework/content/commons/repository/factory/StoreFactory.java
spring-content-commons/src/main/java/org/springframework/content/commons/storeservice/StoreInfo.java
spring-content-rest/src/main/asciidoc/rest-fullyqualifiedlinks.adoc
spring-content-rest/src/main/java/internal/org/springframework/content/rest/contentservice/ContentServiceFactory.java
spring-content-rest/src/main/java/internal/org/springframework/content/rest/contentservice/ContentStoreContentService.java
spring-content-rest/src/main/java/internal/org/springframework/content/rest/controllers/ResourceHandlerMethodArgumentResolver.java
spring-content-rest/src/main/java/internal/org/springframework/content/rest/controllers/StoreRestController.java
spring-content-rest/src/main/java/internal/org/springframework/content/rest/links/ContentLinksResourceProcessor.java
spring-content-rest/src/main/java/internal/org/springframework/content/rest/mappingcontext/ContentPropertyRequest.java
spring-content-rest/src/main/java/internal/org/springframework/content/rest/mappingcontext/ContentPropertyToExportedContext.java
spring-content-rest/src/main/java/internal/org/springframework/content/rest/mappingcontext/ContentPropertyToRequestMappingContext.java
spring-content-rest/src/main/java/internal/org/springframework/content/rest/mappingcontext/RestResourceMappingBuilder.java
spring-content-rest/src/main/java/internal/org/springframework/content/rest/mappings/ContentHandlerMapping.java
spring-content-rest/src/main/java/internal/org/springframework/content/rest/utils/StoreUtils.java
spring-content-rest/src/main/java/org/springframework/content/rest/RestResource.java
spring-content-rest/src/main/java/org/springframework/content/rest/config/HypermediaConfiguration.java
spring-content-rest/src/main/java/org/springframework/content/rest/config/RestConfiguration.java
spring-content-rest/src/test/java/internal/org/springframework/content/rest/it/http_405/MethodNotAllowedExceptionIT.java
spring-content-rest/src/test/java/internal/org/springframework/content/rest/links/ContentLinksResourceProcessorIT.java
spring-content-rest/src/test/java/internal/org/springframework/content/rest/mappings/RestResourceMappingBuilderTest.java
spring-content-rest/src/test/java/internal/org/springframework/content/rest/storedrenditions/StoredRenditionsRestIT.java
spring-content-rest/src/test/java/internal/org/springframework/content/rest/support/TestEntity10Child.java
spring-content-rest/src/test/java/internal/org/springframework/content/rest/support/TestEntity11.java
spring-content-rest/src/test/java/internal/org/springframework/content/rest/support/TestEntity11Store.java
spring-content-rest/src/test/java/internal/org/springframework/content/rest/support/TestEntity5Store.java
spring-content-rest/src/test/java/it/internal/org/springframework/content/rest/controllers/RestResourceMappedRestEndpointsIT.java

feat: add support for configuring exported content URLs

---

spring-content-rest/src/main/java/org/springframework/content/rest/config/RestConfiguration.java

fix: lazy initialize the mapping context

---

spring-content-jpa/src/main/asciidoc/jpa.adoc

docs: update jpa docs to clarify when to create the datasourceInitializer bean

---

spring-content-fs/pom.xml

deps: use org.hibernate.orm:hibernate-core instead of hibernate-core-jakarta

---

spring-content-jpa/src/main/java/internal/org/springframework/content/jpa/store/DefaultJpaStoreImpl.java
spring-content-jpa/src/test/java/internal/org/springframework/content/jpa/store/DefaultJpaStoreImplTest.java

Add check for jakarta entity @Id, fixes issue #1548

---

spring-content-rest/src/main/java/internal/org/springframework/content/rest/contentservice/ContentStoreContentService.java
spring-content-rest/src/test/java/it/internal/org/springframework/content/rest/controllers/Content.java

Puts and posts that dont specify the Content-Type header should return 400 Bad Request

---

spring-content-azure-storage/pom.xml
spring-content-gcs/pom.xml
spring-content-s3/pom.xml
spring-versions-jpa/pom.xml

deps: remove the last vestigages of hibernate-core-jakarta

---

spring-content-commons/src/main/java/org/springframework/content/commons/storeservice/Stores.java
spring-content-fs/src/main/java/org/springframework/content/fs/io/FileSystemResourceLoader.java
spring-content-renditions/src/main/java/internal/org/springframework/renditions/poi/POIServiceImpl.java
spring-content-rest/src/main/java/internal/org/springframework/content/rest/contentservice/StoreContentService.java
spring-content-rest/src/main/java/internal/org/springframework/content/rest/links/ContentLinksResourceProcessor.java
spring-content-rest/src/main/java/internal/org/springframework/content/rest/mappingcontext/ContentPropertyRequest.java
spring-versions-jpa/src/main/java/org/springframework/versions/interceptors/OptimisticLockingInterceptor.java

Fix: https://github.com/paulcwarren/spring-content/issues/1701

fix: add message when use Assert.notNull

---

spring-content-rest/src/main/java/org/springframework/data/rest/extensions/entitycontent/RepositoryEntityMultipartController.java
spring-content-rest/src/test/java/it/internal/org/springframework/content/rest/controllers/ContentEntityRestEndpointsIT.java

fix: multipart/form controller should set filename and content length

---

spring-content-rest/src/main/java/org/springframework/data/rest/extensions/entitycontent/RepositoryEntityMultipartController.java
spring-content-rest/src/test/java/it/internal/org/springframework/content/rest/controllers/ContentEntityRestEndpointsIT.java

Fix multipart request without content

---

spring-content-s3/src/main/asciidoc/s3.adoc

Fix missing line break in s3.adoc

---

spring-content-rest/src/main/java/internal/org/springframework/content/rest/contentservice/AssociativeStoreContentService.java
spring-content-rest/src/main/java/internal/org/springframework/content/rest/contentservice/ContentStoreContentService.java

Handle Spring Boot 3.2.4 ClientAbortExceptions

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
README.md

- required by spring-content-renditions

dev: add libfreetype6 and fontconfig packages

---

spring-content-encryption/src/main/java/org/springframework/content/encryption/keys/DataEncryptionKeyAccessor.java

fix default implementations of addKey and removeKey in DataEncryptionKeyAccessorKeyAccessor

---

pom.xml
spring-content-rest/pom.xml

Reverts paulcwarren/spring-content#2388

Revert "build(deps): bump test-containers.version from 1.17.6 to 1.21.1"
